FROM node:22-alpine3.22

RUN apk add bash dumb-init \
    && rm -rf /var/cache/apk/*

ENV NODE_ENV=development

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

CMD ["npm","run", "start:dev"]

EXPOSE 5000