FROM node:22-alpine3.22

RUN apk add --no-cache bash dumb-init

ENV NODE_ENV=development

WORKDIR /app

COPY package.json package-lock.json ./

RUN --mount=type=cache,target=/root/.npm \
    npm ci

ENTRYPOINT ["dumb-init", "--"]
CMD ["npm", "run", "start:dev"]

EXPOSE 5005